
package server.content;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuditTrail", targetNamespace = "http://interfaces.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuditTrail {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logging", targetNamespace = "http://interfaces.server/", className = "server.content.Logging")
    @ResponseWrapper(localName = "loggingResponse", targetNamespace = "http://interfaces.server/", className = "server.content.LoggingResponse")
    @Action(input = "http://interfaces.server/AuditTrail/loggingRequest", output = "http://interfaces.server/AuditTrail/loggingResponse")
    public boolean logging(
        @WebParam(name = "arg0", targetNamespace = "")
        Transaction arg0);

}
