
package server.content;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuditTrailImplService", targetNamespace = "http://workflow.server/", wsdlLocation = "http://localhost:65000/WS/AuditTrail?wsdl")
public class AuditTrailImplService
    extends Service
{

    private final static URL AUDITTRAILIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUDITTRAILIMPLSERVICE_EXCEPTION;
    private final static QName AUDITTRAILIMPLSERVICE_QNAME = new QName("http://workflow.server/", "AuditTrailImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:65000/WS/AuditTrail?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUDITTRAILIMPLSERVICE_WSDL_LOCATION = url;
        AUDITTRAILIMPLSERVICE_EXCEPTION = e;
    }

    public AuditTrailImplService() {
        super(__getWsdlLocation(), AUDITTRAILIMPLSERVICE_QNAME);
    }

    public AuditTrailImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUDITTRAILIMPLSERVICE_QNAME, features);
    }

    public AuditTrailImplService(URL wsdlLocation) {
        super(wsdlLocation, AUDITTRAILIMPLSERVICE_QNAME);
    }

    public AuditTrailImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUDITTRAILIMPLSERVICE_QNAME, features);
    }

    public AuditTrailImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuditTrailImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuditTrail
     */
    @WebEndpoint(name = "AuditTrailImplPort")
    public AuditTrail getAuditTrailImplPort() {
        return super.getPort(new QName("http://workflow.server/", "AuditTrailImplPort"), AuditTrail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuditTrail
     */
    @WebEndpoint(name = "AuditTrailImplPort")
    public AuditTrail getAuditTrailImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://workflow.server/", "AuditTrailImplPort"), AuditTrail.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUDITTRAILIMPLSERVICE_EXCEPTION!= null) {
            throw AUDITTRAILIMPLSERVICE_EXCEPTION;
        }
        return AUDITTRAILIMPLSERVICE_WSDL_LOCATION;
    }

}
