
package server.content;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Holdings", targetNamespace = "http://interfaces.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Holdings {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<server.content.Bond>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerBonds", targetNamespace = "http://interfaces.server/", className = "server.content.GetCustomerBonds")
    @ResponseWrapper(localName = "getCustomerBondsResponse", targetNamespace = "http://interfaces.server/", className = "server.content.GetCustomerBondsResponse")
    @Action(input = "http://interfaces.server/Holdings/getCustomerBondsRequest", output = "http://interfaces.server/Holdings/getCustomerBondsResponse")
    public List<Bond> getCustomerBonds(
        @WebParam(name = "arg0", targetNamespace = "")
        Client arg0);

}
