
package server.workflow;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthentificationImplService", targetNamespace = "http://workflow.server/", wsdlLocation = "http://localhost:8080/WS/Authenticate?wsdl")
public class AuthentificationImplService
    extends Service
{

    private final static URL AUTHENTIFICATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTIFICATIONIMPLSERVICE_EXCEPTION;
    private final static QName AUTHENTIFICATIONIMPLSERVICE_QNAME = new QName("http://workflow.server/", "AuthentificationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Authenticate?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTIFICATIONIMPLSERVICE_WSDL_LOCATION = url;
        AUTHENTIFICATIONIMPLSERVICE_EXCEPTION = e;
    }

    public AuthentificationImplService() {
        super(__getWsdlLocation(), AUTHENTIFICATIONIMPLSERVICE_QNAME);
    }

    public AuthentificationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTIFICATIONIMPLSERVICE_QNAME, features);
    }

    public AuthentificationImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTIFICATIONIMPLSERVICE_QNAME);
    }

    public AuthentificationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTIFICATIONIMPLSERVICE_QNAME, features);
    }

    public AuthentificationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthentificationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Authentification
     */
    @WebEndpoint(name = "AuthentificationImplPort")
    public Authentification getAuthentificationImplPort() {
        return super.getPort(new QName("http://workflow.server/", "AuthentificationImplPort"), Authentification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authentification
     */
    @WebEndpoint(name = "AuthentificationImplPort")
    public Authentification getAuthentificationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://workflow.server/", "AuthentificationImplPort"), Authentification.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTIFICATIONIMPLSERVICE_EXCEPTION!= null) {
            throw AUTHENTIFICATIONIMPLSERVICE_EXCEPTION;
        }
        return AUTHENTIFICATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
